//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGamesLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGamesLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///.,m
        ///.,m
        ///.,mn
        ///.,mn
        ///.,mnb
        ///.,mnb
        ////.,
        ////.,
        ////.,m
        ////.,m
        ////.,mn
        ////.,mn
        ////.,mnb
        ////.,mnb
        ////dev/null
        ////dev/null
        ////etc/passwd
        ////etc/passwd
        ////usr/group
        ////usr/group
        ///0
        ///0
        ///00
        ///00
        ///000
        ///000
        ///0000
        ///0000
        ///00000
        ///00000
        ///000000
        ///000000
        ///0000000
        ///0000000
        ///00000000
        ///00000000
        ///1
        ///1
        ///10
        ///10
        ///100
        ///100
        ///1029
        ///1029
        ///10293
        ///10293
        ///102938
        ///102938
        ///11
        ///11
        ///111
        ///111
        ///1111
        ///1111
        ///11111
        ///11111
        ///111111
        ///111111
        ///1111111
        ///1111111
        ///11111111
        ///11111111
        ///12
        ///12
        ///1209
        ///1209
        ///123
        ///123 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllWords {
            get {
                return ResourceManager.GetString("AllWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightUp {
            get {
                object obj = ResourceManager.GetObject("LightUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveForward {
            get {
                object obj = ResourceManager.GetObject("MoveForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA
        ///AAAS
        ///AARHUS
        ///AARON
        ///ABA
        ///ABABA
        ///ABACK
        ///ABACUS
        ///ABASE
        ///ABASH
        ///ABATE
        ///ABBAS
        ///ABBE
        ///ABBEY
        ///ABBOT
        ///ABBOTT
        ///ABC
        ///ABDUCT
        ///ABE
        ///ABED
        ///ABEL
        ///ABET
        ///ABHOR
        ///ABIDE
        ///ABJECT
        ///ABJURE
        ///ABLATE
        ///ABLAZE
        ///ABLE
        ///ABNER
        ///ABO
        ///ABOARD
        ///ABODE
        ///ABORT
        ///ABOUND
        ///ABOUT
        ///ABOVE
        ///ABRADE
        ///ABRAM
        ///ABROAD
        ///ABRUPT
        ///ABSENT
        ///ABSORB
        ///ABSURD
        ///ABUSE
        ///ABUT
        ///ABYSS
        ///ACACIA
        ///ACADIA
        ///ACCEDE
        ///ACCENT
        ///ACCEPT
        ///ACCESS
        ///ACCORD
        ///ACCOST
        ///ACCRA
        ///ACCRUE
        ///ACCUSE
        ///ACE
        ///ACETIC
        ///ACHE
        ///ACHING
        ///ACID
        ///ACIDIC
        ///ACKLEY
        ///ACM
        ///ACME
        ///ACORN
        ///ACQUIT
        ///ACRE
        ///ACRID
        ///ACROSS
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextTwistWords {
            get {
                return ResourceManager.GetString("TextTwistWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurnLeft {
            get {
                object obj = ResourceManager.GetObject("TurnLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurnRight {
            get {
                object obj = ResourceManager.GetObject("TurnRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aal
        ///aalii
        ///aam
        ///aani
        ///aardvark
        ///aardwolf
        ///aaronic
        ///aaronical
        ///aaronite
        ///aaronitic
        ///aaru
        ///ab
        ///ababdeh
        ///ababua
        ///abac
        ///abaca
        ///abacate
        ///abacay
        ///abacinate
        ///abacination
        ///abaciscus
        ///abacist
        ///abactinal
        ///abactinally
        ///abaction
        ///abactor
        ///abaculus
        ///abadite
        ///abaff
        ///abaft
        ///abaisance
        ///abaiser
        ///abaissed
        ///abalienate
        ///abalienation
        ///abama
        ///abampere
        ///abandonable
        ///abandoned
        ///abandonedly
        ///abandonee
        ///abandoner
        ///abandonment
        ///abanic
        ///abantes
        ///abaptiston
        ///abarambo
        ///abaris
        ///abarthrosis
        ///abarticular
        ///abarticulation
        ///abas
        ///abased        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnabrigedDictionary {
            get {
                return ResourceManager.GetString("UnabrigedDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10th
        ///1st
        ///2nd
        ///3rd
        ///4th
        ///5th
        ///6th
        ///7th
        ///8th
        ///9th
        ///a
        ///a&amp;m
        ///a&amp;p
        ///a&apos;s
        ///aaa
        ///aaas
        ///aarhus
        ///aaron
        ///aau
        ///aba
        ///ababa
        ///aback
        ///abacus
        ///abalone
        ///abandon
        ///abase
        ///abash
        ///abate
        ///abater
        ///abbas
        ///abbe
        ///abbey
        ///abbot
        ///abbott
        ///abbreviate
        ///abc
        ///abdicate
        ///abdomen
        ///abdominal
        ///abduct
        ///abe
        ///abed
        ///abel
        ///abelian
        ///abelson
        ///aberdeen
        ///abernathy
        ///aberrant
        ///aberrate
        ///abet
        ///abetted
        ///abetting
        ///abeyance
        ///abeyant
        ///abhorred
        ///abhorrent
        ///abide
        ///abidjan
        ///abigail
        ///abject
        ///ablate
        ///ablaze
        ///able
        ///ablution
        ///abner
        ///abnormal
        ///abo
        ///aboard
        ///abode
        ///aboli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnixWords {
            get {
                return ResourceManager.GetString("UnixWords", resourceCulture);
            }
        }
    }
}
